language: python
python:
  - "3.6"
install:
  - "python setup.py install"
  - "pip install coveralls"
env:
  global:
    - PYTHONPATH=$PYTHONPATH:/home/bigjerbd/Workspace/Pydarg/pydarg
script:
  - py.test
after_success:
  - coveralls
